# Generated by Django 2.1.4 on 2019-01-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcasestep',
            name='appevelement',
            field=models.CharField(max_length=800, verbose_name='控件元素'),
        ),
    ]
